---
title: "Jasmine"
output: html_document
---

Create data
```{r}
s_mobile$mou_log <- log(s_mobile$mou + 1)
train <- s_mobile %>%
  filter(representative == 0)%>%
  mutate(cweight = ifelse(churn == 'yes', 1L, 49L))

representative <- s_mobile %>%
  filter(representative == 1)
```

Logistic model

```{r}
result <- logistic(
  train, 
  rvar = "churn", 
  evar = c(
    "changer", "changem", "revenue", "overage", "roam", "conference", 
    "months", "uniqsubs", "retcalls", "dropvce", 
    "eqpdays", "refurb",  "highcreditr", "mcycle", 
   "travel", "region", "occupation", "mou_log"
  ), 
  lev = "yes", 
  wts = "cweight", 
  check = "standardize"
)
summary(result)
pred <- predict(result, pred_data = representative)
plot(result, plots = "coef", custom = FALSE)
#print(pred, n = 10)
representative <- store(representative, pred, name = "pred_logit")
```

Show the result in graph.
```{r}
coef_table  <- write.coeff(result, sort = TRUE,intercept = FALSE) %>%
  select(label,OR,p.value,importance)

coef_table

coef_table %>%
  ggplot(aes(x = fct_reorder(label, importance), y = importance))+
  geom_bar(stat = 'identity') +
  coord_flip()+
  geom_hline(yintercept = 1,linetype = 'dotted',color = 'red') +
  labs(x = 'variables')

```


central singapore：merlion park, singapore landmerk and main tourist attraction, located near one fullerton (浮尔顿酒店)， near central business district.


